<?php

use Drupal\node\Entity\Node;
use Drupal\Core\Url;


/**
 * Implements hook_preprocess_HOOK() for page templates.
 */
function myadmin_preprocess_page(&$variables)
{
  // Charger les 5 derniers articles publiés
  // $nids = \Drupal::entityQuery('node')
  //   ->condition('type', 'cart')
  //   ->range(0, 5)
  //   ->sort('created', 'DESC')
  //   ->execute();

  // $nodes = Node::loadMultiple($nids);
  // $articles = [];
  // foreach ($nodes as $node) {
  //   $articles[] = [
  //     'id' => $node->id(),
  //     'title' => $node->getTitle(),
  //     'created' => \Drupal::service('date.formatter')->format($node->getCreatedTime(), 'short'),
  //   ];
  // }
  // // Injecter dans drupalSettings
  // $variables['#attached']['drupalSettings']['vueArticles'] = $articles;
  
  $current_user = \Drupal::currentUser();
  $data = [
    'isLoggedIn' => $current_user->isAuthenticated(), // TRUE ou FALSE
    'uid' => $current_user->id(),
    'roles' => $current_user->getRoles(),
    'username' => $current_user->getAccountName(),
    'baseUrl' => Url::fromRoute('<front>', [], ['absolute' => TRUE])->toString(),
    'menu' => [
      ["id" => 1, "name" => "Caisse", "path" => "/", "icon" => "fas fa-home", "paths" => ["/", "/caisse", "/fr", "/fr/frontdesk"], 'roles' => ['caissier', 'docteur', 'administrator']],
      ["name" => "Commandes", "path" => "/commandes", "icon" => "fas fa-shopping-cart", "paths" => ["/commandes", "/fr/commandes"], 'roles' => ['caissier', 'docteur', 'administrator']],
      ["name" => "Patients", "path" => "/patients", "icon" => "fas fa-users", "paths" => ["/patients", "/fr/patients"], 'roles' => ['docteur', 'administrator']],
      ["name" => "Consulter", "path" => "/consultations", "icon" => "fas fa-stethoscope", "paths" => ["/consultations", "/consultations/edit", "/fr/consultations", "/fr/consultations/edit"], 'roles' => ['docteur', 'administrator']],
      ["name" => "Assistant IA", "path" => "/assist", "icon" => "fas fa-robot", "paths" => ["/assist", "/fr/assist"], 'roles' => ['docteur', 'administrator']],
      ["name" => "Stocks", "path" => "/stocks", "icon" => "fas fa-boxes", "paths" => ["/stocks", "/fr/stocks"], 'roles' => ['caissier', 'docteur', 'administrator']],
    ]
  ];

  $variables['#attached']['drupalSettings']['data'] = $data;
}
